In [17]:
import pandas as pd
import numpy as np

## 1 Creating a Dataframe from an Arrays

### option 1

In [18]:
# creating an Array
data = np.array([[1,2],[3,4],[5,6]])

In [19]:
#creating an dataframe
df = pd.DataFrame(data, index=['row1', 'row2', 'row3'], #index represents row name
                  columns = ['column1', 'columns2']) #column represent column name

In [20]:
#showing dataframe
df

      column1  columns2
row1        1         2
row2        3         4
row3        5         6

### option 2 (list)

In [21]:
#creating a list
data = [[1,2],[3,4],[5,6]]

In [22]:
#creating an dataframe
df = pd.DataFrame(data, index=['row1', 'row2', 'row3'], #index represents row name
                  columns = ['column1', 'columns2']) #column represent column name

In [24]:
#showing dataframe
df

      column1  columns2
row1        1         2
row2        3         4
row3        5         6

## 2 Creating a Dataframe from Dictionary

In [25]:
#creating a list
states = ['Maharashtra', 'Rajasthan', 'Gujarat']
population = [20358465, 57486543, 6847365]

In [28]:
#storing lists within dictionary
dict_s = {'States': states, 'Population': population}

In [31]:
#creating a dataframe
df_p = pd.DataFrame(dict_s)

In [32]:
#showing dataframe
df_p

        States  Population
0  Maharashtra    20358465
1    Rajasthan    57486543
2      Gujarat     6847365

## 3 From CSV File

In [35]:
#importing or reading csv files
df = pd.read_csv('generated_dataset.csv')

In [37]:
#showing dataframe
df

,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,Feature_10,...,Feature_13,Feature_14,Feature_15,Feature_16,Feature_17,Feature_18,Feature_19,Feature_20,Category,Status
0,102,435,860,270,106,71,700,20,614,121,...,330,458,87,372,99,871,663,130,C,Inactive
1,661,308,769,343,491,413,805,385,191,955,...,459,313,21,252,747,856,560,474,B,Active
2,58,510,681,475,699,975,782,189,957,686,...,875,566,243,831,504,130,484,818,A,Active
3,646,20,840,166,273,387,600,315,13,241,...,564,897,339,91,366,955,454,427,A,Active
4,508,775,942,34,205,80,931,561,871,387,...,565,105,771,821,476,702,401,729,D,Inactive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,526,689,966,377,586,103,805,679,961,626,...,363,784,134,373,231,38,963,802,D,Active
996,818,46,35,831,94,984,360,524,145,916,...,227,753,519,815,852,554,755,180,B,Inactive
997,500,596,154,786,534,626,817,434,810,98,...,562,361,111,452,755,168,583,138,A,Inactive
998,847,230,238,983,252,980,435,918,560,421,...,262,833,221,76,61,470,156,805,D,Active
999,124,740,851,160,540,625,590,534,105,130,...,684,775,853,884,796,1,232,368,C,Inactive