In [1]:
import pandas as pd

In [3]:
# reading a csv file
df_exams =  pd.read_csv('student_performance.csv')

In [5]:
df_exams

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result
0,1,Male,21,14,93,93,1,71,74,Pass
1,2,Female,21,21,94,69,1,95,79,Pass
2,3,Male,17,24,83,73,8,50,53,Pass
3,4,Male,19,28,52,99,4,59,74,Fail
4,5,Male,18,9,86,98,1,63,87,Pass
...,...,...,...,...,...,...,...,...,...,...
495,496,Male,21,21,73,83,0,40,77,Pass
496,497,Male,21,18,69,63,10,96,55,Pass
497,498,Female,20,35,86,85,6,68,41,Fail
498,499,Male,18,28,53,82,5,84,79,Fail
499,500,Female,17,39,77,72,1,88,56,Pass

In [7]:
#displaying first five rows
df_exams.head()

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result
0,1,Male,21,14,93,93,1,71,74,Pass
1,2,Female,21,21,94,69,1,95,79,Pass
2,3,Male,17,24,83,73,8,50,53,Pass
3,4,Male,19,28,52,99,4,59,74,Fail
4,5,Male,18,9,86,98,1,63,87,Pass

In [11]:
#displaying last five rows
df_exams.tail()

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result
495,496,Male,21,21,73,83,0,40,77,Pass
496,497,Male,21,18,69,63,10,96,55,Pass
497,498,Female,20,35,86,85,6,68,41,Fail
498,499,Male,18,28,53,82,5,84,79,Fail
499,500,Female,17,39,77,72,1,88,56,Pass

In [14]:
#display first n rows
df_exams.head(15)

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result
0,1,Male,21,14,93,93,1,71,74,Pass
1,2,Female,21,21,94,69,1,95,79,Pass
2,3,Male,17,24,83,73,8,50,53,Pass
3,4,Male,19,28,52,99,4,59,74,Fail
4,5,Male,18,9,86,98,1,63,87,Pass
5,6,Female,17,38,92,81,10,54,84,Pass
6,7,Male,18,10,89,90,8,87,59,Pass
7,8,Male,22,6,75,85,8,46,95,Pass
8,9,Male,18,17,72,83,0,60,88,Pass
9,10,Female,19,15,93,85,10,81,52,Pass
10,11,Male,22,27,88,51,2,65,77,Pass
11,12,Male,18,20,64,64,3,83,88,Pass
12,13,Male,22,35,98,83,6,95,85,Pass
13,14,Male,18,15,53,85,9,53,88,Fail
14,15,Female,19,20,78,55,3,96,47,Fail

In [16]:
#display last n rows
df_exams.tail(15)

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result
485,486,Female,18,11,84,55,7,57,42,Fail
486,487,Male,20,13,78,71,10,56,53,Pass
487,488,Female,17,12,64,67,3,51,99,Pass
488,489,Male,22,27,82,57,1,45,52,Pass
489,490,Male,17,33,56,88,9,65,84,Fail
490,491,Female,20,22,61,81,10,66,71,Pass
491,492,Male,22,35,98,82,8,47,73,Pass
492,493,Male,18,34,79,65,4,58,84,Pass
493,494,Female,19,39,70,61,3,99,58,Pass
494,495,Male,17,22,80,87,1,81,98,Pass
495,496,Male,21,21,73,83,0,40,77,Pass
496,497,Male,21,18,69,63,10,96,55,Pass
497,498,Female,20,35,86,85,6,68,41,Fail
498,499,Male,18,28,53,82,5,84,79,Fail
499,500,Female,17,39,77,72,1,88,56,Pass

In [22]:
# getting access to shape attribute of dataframe ie number of rows and columns
df_exams.shape

(500, 10)

In [35]:
# displaying n number of rows
pd.set_option("display.max_rows", 500) #if df has more than n(500) don't print everything
df_exams

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result
0,1,Male,21,14,93,93,1,71,74,Pass
1,2,Female,21,21,94,69,1,95,79,Pass
2,3,Male,17,24,83,73,8,50,53,Pass
3,4,Male,19,28,52,99,4,59,74,Fail
4,5,Male,18,9,86,98,1,63,87,Pass
5,6,Female,17,38,92,81,10,54,84,Pass
6,7,Male,18,10,89,90,8,87,59,Pass
7,8,Male,22,6,75,85,8,46,95,Pass
8,9,Male,18,17,72,83,0,60,88,Pass
9,10,Female,19,15,93,85,10,81,52,Pass
10,11,Male,22,27,88,51,2,65,77,Pass
11,12,Male,18,20,64,64,3,83,88,Pass
12,13,Male,22,35,98,83,6,95,85,Pass
13,14,Male,18,15,53,85,9,53,88,Fail
14,15,Female,19,20,78,55,3,96,47,Fail
15,16,Male,18,12,71,88,1,76,82,Pass
16,17,Female,18,8,74,91,6,97,59,Pass
17,18,Female,18,8,62,61,5,60,99,Pass
18,19,Female,17,29,67,52,2,57,72,Pass
19,20,Male,17,7,82,94,5,44,65,Pass
20,21,Female,17,36,65,67,10,42,78,Pass
21,22,Male,19,7,94,89,5,62,60,Pass
22,23,Female,22,31,91,70,4,65,92,Pass
23,24,Female,21,33,93,64,3,76,88,Pass
24,25,Female,18,36,51,82,9,63,81,Fail
25,26,Female,18,23,84,84,0,88,82,Pass
26,27,Female,19,25,91,75,9,58,93,Pass
27,28,Female,18,9,83,57,5,90,80,Pass
28,29,Female,17,22,79,85,1,64,48,Fail
29,30,Female,21,32,62,97,2,60,63,Pass
30,31,Male,20,26,62,79,7,51,76,Pass
31,32,Male,18,25,67,72,9,96,88,Pass
32,33,Female,17,10,81,91,5,80,80,Pass
33,34,Female,20,5,81,93,2,72,56,Pass
34,35,Female,21,9,84,63,6,89,63,Pass
35,36,Male,20,16,88,63,3,92,60,Pass
36,37,Female,17,30,95,51,8,43,90,Pass
37,38,Male,22,38,78,86,4,81,98,Pass
38,39,Male,22,18,98,54,2,96,78,Pass
39,40,Male,20,30,78,87,1,46,94,Pass
40,41,Male,19,31,93,94,10,61,80,Pass
41,42,Male,20,13,65,90,1,94,78,Pass
42,43,Female,18,30,93,96,2,72,52,Pass
43,44,Female,18,26,96,63,1,56,50,Pass
44,45,Female,22,34,59,88,3,63,85,Fail
45,46,Female,19,21,79,74,1,73,58,Pass
46,47,Female,17,30,74,69,9,67,50,Pass
47,48,Male,18,5,88,51,8,97,52,Pass
48,49,Female,22,12,69,88,1,82,85,Pass
49,50,Female,21,39,54,55,8,80,84,Fail
50,51,Male,22,19,50,66,5,78,40,Fail
51,52,Female,18,26,79,74,0,61,79,Pass
52,53,Male,18,18,98,77,3,88,83,Pass
53,54,Female,22,30,52,51,0,56,58,Fail
54,55,Male,17,32,94,84,5,73,51,Pass
55,56,Female,20,27,63,86,3,45,47,Fail
56,57,Female,18,18,79,54,2,85,47,Fail
57,58,Male,22,28,99,50,2,45,92,Pass
58,59,Male,22,6,53,89,8,73,84,Fail
59,60,Male,19,30,67,61,5,40,51,Pass
60,61,Male,20,18,86,85,8,49,87,Pass
61,62,Male,21,11,74,94,4,60,72,Pass
62,63,Male,17,7,97,72,1,44,84,Pass
63,64,Male,21,27,50,96,7,41,65,Fail
64,65,Male,20,22,95,80,4,61,78,Pass
65,66,Female,20,39,64,60,1,87,67,Pass
66,67,Female,20,19,58,59,3,96,97,Fail
67,68,Male,21,29,64,52,8,41,44,Fail
68,69,Female,20,32,98,63,3,49,47,Fail
69,70,Female,22,14,73,65,3,73,64,Pass
70,71,Female,21,21,53,59,1,55,66,Fail
71,72,Female,20,26,61,78,5,87,85,Pass
72,73,Male,22,30,86,59,10,90,62,Pass
73,74,Female,19,29,86,61,1,78,69,Pass
74,75,Male,20,21,92,79,6,61,84,Pass
75,76,Female,21,17,55,90,2,51,86,Fail
76,77,Female,18,24,88,50,2,63,62,Pass
77,78,Female,20,29,95,54,4,86,88,Pass
78,79,Male,18,8,73,69,2,79,86,Pass
79,80,Female,22,14,60,57,1,77,59,Pass
80,81,Male,19,7,62,92,9,99,57,Pass
81,82,Female,17,22,83,61,8,98,57,Pass
82,83,Male,19,26,74,50,1,49,41,Fail
83,84,Female,20,38,56,69,10,74,43,Fail
84,85,Male,18,12,53,77,1,90,69,Fail
85,86,Male,18,23,57,92,7,88,72,Fail
86,87,Female,21,10,69,86,8,71,75,Pass
87,88,Male,18,30,78,96,6,46,57,Pass
88,89,Female,21,38,100,86,2,60,76,Pass
89,90,Female,22,10,94,61,8,59,58,Pass
90,91,Female,17,37,95,86,2,65,86,Pass
91,92,Female,20,26,59,98,4,43,67,Fail
92,93,Female,21,25,92,98,8,85,79,Pass
93,94,Female,17,10,83,93,2,91,59,Pass
94,95,Female,18,10,75,77,6,61,88,Pass
95,96,Female,18,8,90,96,0,54,72,Pass
96,97,Female,17,34,98,64,3,95,51,Pass
97,98,Female,18,15,52,55,3,79,97,Fail
98,99,Female,22,34,55,93,6,60,90,Fail
99,100,Male,22,35,54,69,7,54,54,Fail
100,101,Male,17,28,54,99,0,61,80,Fail
101,102,Female,21,13,96,63,4,91,78,Pass
102,103,Female,21,7,72,51,6,67,41,Fail
103,104,Female,17,35,98,58,3,53,68,Pass
104,105,Female,21,28,58,86,3,66,80,Fail
105,106,Female,21,35,84,69,3,80,49,Fail
106,107,Female,22,10,69,75,5,79,41,Fail
107,108,Female,21,6,98,78,6,97,90,Pass
108,109,Female,19,24,91,50,1,67,50,Pass
109,110,Male,20,32,84,84,4,65,52,Pass
110,111,Female,18,15,99,55,3,88,49,Fail
111,112,Male,19,8,67,86,2,41,53,Pass
112,113,Female,21,19,66,54,6,64,57,Pass
113,114,Female,22,10,73,82,10,95,90,Pass
114,115,Male,17,34,52,98,5,42,93,Fail
115,116,Female,21,6,81,63,6,47,48,Fail
116,117,Male,22,19,84,61,4,83,96,Pass
117,118,Female,20,15,87,91,5,72,78,Pass
118,119,Female,21,12,62,69,4,81,67,Pass
119,120,Male,17,30,96,99,6,91,42,Fail
120,121,Female,22,9,74,73,1,74,59,Pass
121,122,Male,22,10,58,92,10,45,45,Fail
122,123,Female,22,30,53,83,4,78,66,Fail
123,124,Male,20,8,63,74,5,91,92,Pass
124,125,Male,21,23,86,99,5,62,41,Fail
125,126,Female,20,24,83,78,4,64,68,Pass
126,127,Female,18,37,60,88,9,98,77,Pass
127,128,Male,18,24,90,80,6,89,42,Fail
128,129,Female,21,16,52,96,9,82,55,Fail
129,130,Female,20,5,77,92,7,58,69,Pass
130,131,Female,17,30,78,99,6,44,79,Pass
131,132,Male,22,18,58,72,4,90,41,Fail
132,133,Male,22,15,52,93,0,50,56,Fail
133,134,Male,21,17,74,87,4,95,80,Pass
134,135,Male,18,7,83,69,9,51,51,Pass
135,136,Male,18,37,61,72,1,49,74,Pass
136,137,Male,22,10,91,94,4,47,82,Pass
137,138,Male,21,14,58,65,4,63,40,Fail
138,139,Male,20,9,64,99,1,99,94,Pass
139,140,Male,18,27,89,91,4,67,84,Pass
140,141,Female,20,14,74,57,3,80,54,Pass
141,142,Male,18,6,54,99,0,75,65,Fail
142,143,Female,18,17,60,70,2,76,76,Pass
143,144,Female,19,6,83,50,0,60,60,Pass
144,145,Female,18,24,73,57,10,47,88,Pass
145,146,Male,17,5,64,78,4,94,70,Pass
146,147,Male,21,13,87,81,3,48,64,Pass
147,148,Male,21,21,57,87,6,86,62,Fail
148,149,Male,20,13,54,54,4,54,63,Fail
149,150,Female,18,15,97,96,9,87,96,Pass
150,151,Male,17,19,75,71,3,85,77,Pass
151,152,Male,20,28,67,96,1,79,67,Pass
152,153,Male,19,39,55,83,3,57,60,Fail
153,154,Male,20,34,86,50,1,81,93,Pass
154,155,Male,20,35,97,75,7,99,82,Pass
155,156,Female,18,9,62,92,2,59,57,Pass
156,157,Male,19,18,77,59,8,45,75,Pass
157,158,Female,20,15,54,79,3,51,74,Fail
158,159,Male,17,13,62,99,5,41,84,Pass
159,160,Female,17,38,66,67,9,46,94,Pass
160,161,Male,21,16,99,66,4,55,48,Fail
161,162,Male,19,39,89,75,9,42,92,Pass
162,163,Female,19,39,94,57,0,84,77,Pass
163,164,Female,21,5,81,96,8,42,97,Pass
164,165,Female,20,26,78,89,0,66,69,Pass
165,166,Male,19,33,100,98,7,89,99,Pass
166,167,Female,17,12,52,61,8,82,83,Fail
167,168,Male,17,15,89,76,8,79,73,Pass
168,169,Male,18,18,83,57,0,77,71,Pass
169,170,Female,19,34,89,74,1,72,42,Fail
170,171,Female,20,39,76,95,0,67,42,Fail
171,172,Male,21,25,62,53,9,40,67,Pass
172,173,Male,21,9,94,82,1,94,83,Pass
173,174,Female,20,23,82,50,9,47,54,Pass
174,175,Female,22,18,55,68,7,76,80,Fail
175,176,Female,18,30,73,80,4,71,62,Pass
176,177,Male,21,8,68,65,10,99,79,Pass
177,178,Male,19,29,65,63,6,87,50,Pass
178,179,Male,18,29,89,97,1,82,87,Pass
179,180,Male,19,22,77,54,7,76,71,Pass
180,181,Male,17,12,82,90,10,43,97,Pass
181,182,Male,18,18,97,75,5,69,98,Pass
182,183,Female,21,36,90,77,7,45,96,Pass
183,184,Male,18,37,62,51,0,85,93,Pass
184,185,Male,18,27,92,99,0,93,75,Pass
185,186,Male,18,19,94,55,6,58,99,Pass
186,187,Female,22,37,74,58,7,71,72,Pass
187,188,Male,18,29,91,82,2,48,63,Pass
188,189,Male,19,21,85,90,4,51,78,Pass
189,190,Female,17,37,76,74,0,50,73,Pass
190,191,Male,20,6,87,97,6,85,95,Pass
191,192,Male,18,18,56,62,4,94,67,Fail
192,193,Male,21,10,54,58,7,55,76,Fail
193,194,Male,18,10,92,62,7,40,46,Fail
194,195,Male,21,7,94,80,8,84,43,Fail
195,196,Female,19,11,100,90,6,94,76,Pass
196,197,Female,21,12,80,60,10,92,95,Pass
197,198,Female,20,19,72,53,0,60,40,Fail
198,199,Male,17,33,91,83,2,69,40,Fail
199,200,Male,21,37,59,87,7,52,86,Fail
200,201,Male,21,34,81,95,2,73,59,Pass
201,202,Female,17,31,92,53,7,43,58,Pass
202,203,Male,20,33,79,87,0,67,68,Pass
203,204,Male,18,37,88,68,4,77,49,Fail
204,205,Female,21,31,80,55,3,97,99,Pass
205,206,Male,17,37,67,83,4,70,57,Pass
206,207,Female,19,8,85,67,7,98,67,Pass
207,208,Female,17,26,51,62,9,94,74,Fail
208,209,Female,19,6,63,90,3,66,82,Pass
209,210,Male,20,14,62,72,10,44,86,Pass
210,211,Male,18,9,78,68,3,64,70,Pass
211,212,Male,17,14,61,94,2,42,66,Pass
212,213,Male,22,37,88,60,6,72,50,Pass
213,214,Male,21,17,51,50,2,43,88,Fail
214,215,Male,20,35,81,73,2,64,88,Pass
215,216,Male,17,28,62,56,10,59,77,Pass
216,217,Female,21,19,95,74,9,73,44,Fail
217,218,Male,17,33,76,70,4,65,47,Fail
218,219,Female,19,12,98,64,4,44,73,Pass
219,220,Male,17,9,90,50,5,74,87,Pass
220,221,Male,22,33,66,61,7,67,91,Pass
221,222,Male,17,8,89,56,9,68,95,Pass
222,223,Female,17,16,80,64,5,48,51,Pass
223,224,Female,22,6,83,70,0,91,77,Pass
224,225,Female,20,31,73,68,7,77,40,Fail
225,226,Female,17,35,94,78,7,89,70,Pass
226,227,Male,22,30,84,74,8,45,43,Fail
227,228,Female,21,31,97,82,8,58,88,Pass
228,229,Male,19,9,55,98,1,99,84,Fail
229,230,Male,19,24,68,81,1,83,89,Pass
230,231,Female,17,15,79,98,2,96,44,Fail
231,232,Female,20,14,56,84,0,50,69,Fail
232,233,Female,20,10,59,93,3,41,95,Fail
233,234,Female,21,12,90,87,3,86,63,Pass
234,235,Female,17,27,81,75,8,83,98,Pass
235,236,Female,19,30,83,60,8,83,42,Fail
236,237,Female,20,16,77,84,8,48,50,Pass
237,238,Female,17,30,64,57,9,60,84,Pass
238,239,Male,20,17,79,95,6,63,43,Fail
239,240,Female,22,22,86,63,1,73,65,Pass
240,241,Female,20,29,78,59,9,61,66,Pass
241,242,Male,19,37,71,51,4,42,85,Pass
242,243,Female,18,16,53,95,3,51,93,Fail
243,244,Male,21,8,69,58,10,67,82,Pass
244,245,Male,21,9,81,52,7,69,66,Pass
245,246,Female,19,12,85,70,1,65,81,Pass
246,247,Male,20,32,99,75,5,87,90,Pass
247,248,Male,17,35,53,57,4,60,89,Fail
248,249,Male,20,13,76,97,1,67,45,Fail
249,250,Male,19,33,66,51,10,95,98,Pass
250,251,Female,21,18,61,55,9,65,54,Pass
251,252,Male,20,26,71,77,0,72,92,Pass
252,253,Female,21,15,66,78,7,60,69,Pass
253,254,Male,17,27,59,75,1,74,81,Fail
254,255,Male,21,5,50,74,6,91,76,Fail
255,256,Male,21,25,71,61,8,73,97,Pass
256,257,Male,18,30,75,54,8,80,76,Pass
257,258,Female,18,27,67,83,7,90,81,Pass
258,259,Female,22,5,99,97,10,86,99,Pass
259,260,Male,18,19,63,86,9,57,76,Pass
260,261,Male,21,25,96,64,8,97,74,Pass
261,262,Female,19,13,78,93,1,50,62,Pass
262,263,Male,21,13,61,85,5,96,45,Fail
263,264,Male,19,14,85,64,3,62,43,Fail
264,265,Male,19,30,84,92,3,87,57,Pass
265,266,Female,18,39,61,97,4,61,99,Pass
266,267,Female,20,29,56,72,2,56,48,Fail
267,268,Female,17,30,78,55,0,44,88,Pass
268,269,Male,18,15,60,95,7,83,68,Pass
269,270,Male,18,6,82,99,4,50,52,Pass
270,271,Female,20,11,55,93,2,69,98,Fail
271,272,Female,17,22,96,92,9,54,86,Pass
272,273,Female,21,31,64,94,6,66,91,Pass
273,274,Female,22,38,81,70,6,74,56,Pass
274,275,Male,22,31,100,72,0,72,84,Pass
275,276,Female,21,21,60,92,8,59,71,Pass
276,277,Male,18,28,72,65,1,55,87,Pass
277,278,Female,17,29,75,96,4,73,61,Pass
278,279,Male,18,11,83,64,4,41,43,Fail
279,280,Female,19,10,95,74,7,74,44,Fail
280,281,Female,18,28,83,85,7,79,76,Pass
281,282,Female,18,37,78,60,6,95,80,Pass
282,283,Female,21,33,53,64,6,67,88,Fail
283,284,Male,21,26,66,53,10,86,52,Pass
284,285,Female,21,30,84,70,5,78,73,Pass
285,286,Male,22,32,62,62,5,45,84,Pass
286,287,Male,19,25,90,71,10,48,61,Pass
287,288,Male,21,11,88,68,8,59,92,Pass
288,289,Male,17,21,64,83,5,99,98,Pass
289,290,Female,22,24,78,63,1,40,62,Pass
290,291,Male,20,24,78,53,1,47,90,Pass
291,292,Male,17,26,60,97,4,94,42,Fail
292,293,Male,17,32,81,95,3,62,81,Pass
293,294,Female,21,11,51,76,10,42,73,Fail
294,295,Female,20,5,96,78,1,43,71,Pass
295,296,Female,20,36,63,96,2,97,84,Pass
296,297,Female,22,17,69,77,6,64,90,Pass
297,298,Male,20,34,71,84,7,86,97,Pass
298,299,Male,19,27,60,57,5,77,88,Pass
299,300,Female,21,23,76,65,10,54,60,Pass
300,301,Male,20,36,52,91,4,60,85,Fail
301,302,Male,22,34,66,85,0,74,83,Pass
302,303,Male,19,33,93,79,7,96,60,Pass
303,304,Female,18,33,77,67,2,92,83,Pass
304,305,Female,18,34,78,51,5,92,50,Pass
305,306,Male,19,20,70,98,2,85,78,Pass
306,307,Female,22,23,96,62,6,91,43,Fail
307,308,Female,19,22,65,53,6,53,90,Pass
308,309,Female,21,5,86,75,8,75,40,Fail
309,310,Female,21,18,69,74,4,51,67,Pass
310,311,Female,18,6,55,79,7,56,63,Fail
311,312,Male,20,32,68,60,9,78,74,Pass
312,313,Female,22,34,54,56,9,48,52,Fail
313,314,Male,18,8,52,80,7,74,86,Fail
314,315,Male,20,5,50,93,0,99,73,Fail
315,316,Female,20,12,87,59,4,52,50,Pass
316,317,Male,21,33,64,88,2,54,75,Pass
317,318,Male,17,7,83,62,0,57,90,Pass
318,319,Male,17,36,84,80,3,90,56,Pass
319,320,Female,19,14,98,56,7,72,74,Pass
320,321,Female,21,14,74,98,2,45,99,Pass
321,322,Male,20,23,73,91,9,98,57,Pass
322,323,Female,22,38,61,91,1,66,79,Pass
323,324,Female,17,37,67,85,10,62,61,Pass
324,325,Female,20,27,64,69,8,98,96,Pass
325,326,Female,17,32,93,53,9,66,63,Pass
326,327,Male,17,36,65,56,4,73,97,Pass
327,328,Male,17,11,76,50,6,95,58,Pass
328,329,Female,22,33,57,93,10,85,76,Fail
329,330,Female,21,12,95,94,10,77,78,Pass
330,331,Male,22,5,74,91,1,53,60,Pass
331,332,Male,18,7,66,96,8,75,47,Fail
332,333,Female,20,28,78,62,8,92,67,Pass
333,334,Male,21,27,57,71,3,47,44,Fail
334,335,Female,21,12,64,70,3,74,56,Pass
335,336,Female,21,7,76,71,5,58,76,Pass
336,337,Male,21,37,95,77,9,69,75,Pass
337,338,Male,22,32,99,58,9,53,93,Pass
338,339,Female,21,12,56,75,9,98,58,Fail
339,340,Female,19,38,52,58,5,59,66,Fail
340,341,Male,20,39,78,64,0,88,92,Pass
341,342,Female,21,36,93,59,8,64,73,Pass
342,343,Male,20,28,73,73,1,79,50,Pass
343,344,Female,19,18,52,91,4,63,93,Fail
344,345,Male,19,36,69,57,8,53,84,Pass
345,346,Male,20,20,95,73,3,65,86,Pass
346,347,Male,17,8,64,65,10,77,51,Pass
347,348,Female,18,25,74,98,2,62,93,Pass
348,349,Female,17,18,79,75,6,61,60,Pass
349,350,Male,17,35,63,76,5,87,93,Pass
350,351,Female,22,22,56,86,7,96,50,Fail
351,352,Male,17,11,66,53,2,58,78,Pass
352,353,Male,21,14,93,99,4,85,67,Pass
353,354,Female,22,11,69,73,9,90,44,Fail
354,355,Female,22,37,85,68,3,42,56,Pass
355,356,Male,19,27,58,85,3,81,95,Fail
356,357,Female,17,25,87,88,3,58,59,Pass
357,358,Female,19,23,97,59,9,48,80,Pass
358,359,Male,20,23,71,74,7,67,85,Pass
359,360,Male,18,33,51,67,5,59,97,Fail
360,361,Female,22,22,73,68,2,84,51,Pass
361,362,Male,20,6,57,85,9,46,45,Fail
362,363,Male,20,5,60,59,4,53,56,Pass
363,364,Female,21,9,62,82,5,48,90,Pass
364,365,Male,18,24,66,99,4,98,58,Pass
365,366,Male,20,15,57,54,5,99,65,Fail
366,367,Female,20,6,70,96,7,94,87,Pass
367,368,Female,18,7,67,98,6,96,83,Pass
368,369,Male,18,27,79,84,4,99,83,Pass
369,370,Male,20,16,67,93,9,58,91,Pass
370,371,Female,18,24,95,83,5,86,71,Pass
371,372,Female,20,9,96,82,3,91,45,Fail
372,373,Female,20,34,80,70,8,53,94,Pass
373,374,Female,21,13,87,66,3,95,97,Pass
374,375,Male,17,38,81,71,0,77,75,Pass
375,376,Female,20,39,60,97,6,92,77,Pass
376,377,Female,19,26,94,86,6,75,50,Pass
377,378,Male,22,28,74,64,3,79,72,Pass
378,379,Female,17,21,82,84,2,56,63,Pass
379,380,Male,17,14,87,77,7,69,62,Pass
380,381,Female,17,34,90,56,4,48,54,Pass
381,382,Female,21,27,57,81,9,72,66,Fail
382,383,Female,20,36,60,60,6,95,50,Pass
383,384,Male,21,21,71,59,3,91,96,Pass
384,385,Male,20,21,100,58,3,64,90,Pass
385,386,Female,21,18,73,63,7,53,89,Pass
386,387,Male,21,13,90,62,7,50,56,Pass
387,388,Male,22,6,66,74,1,92,90,Pass
388,389,Male,19,29,61,51,1,74,92,Pass
389,390,Male,21,13,95,84,2,80,53,Pass
390,391,Male,22,26,81,56,2,98,66,Pass
391,392,Male,18,8,64,70,0,53,57,Pass
392,393,Female,19,30,65,67,2,69,67,Pass
393,394,Female,21,33,71,52,5,80,90,Pass
394,395,Male,17,38,77,91,7,43,86,Pass
395,396,Female,18,27,69,88,9,98,86,Pass
396,397,Female,18,15,82,90,5,43,43,Fail
397,398,Female,22,10,59,98,4,67,46,Fail
398,399,Female,18,22,89,60,3,47,84,Pass
399,400,Male,19,25,81,88,2,41,74,Pass
400,401,Female,21,38,99,73,3,80,87,Pass
401,402,Female,21,21,82,95,6,85,48,Fail
402,403,Male,17,29,51,68,0,61,47,Fail
403,404,Male,22,16,82,53,6,80,91,Pass
404,405,Female,17,27,82,75,0,95,84,Pass
405,406,Female,18,26,90,87,1,94,56,Pass
406,407,Female,17,25,62,91,3,55,56,Pass
407,408,Female,19,31,79,81,0,68,88,Pass
408,409,Female,21,35,82,88,10,88,72,Pass
409,410,Female,18,10,62,94,10,87,71,Pass
410,411,Male,17,31,75,95,10,69,47,Fail
411,412,Female,22,38,71,85,8,51,58,Pass
412,413,Female,19,16,88,89,5,74,77,Pass
413,414,Male,19,11,51,86,0,50,42,Fail
414,415,Male,17,14,87,82,0,85,98,Pass
415,416,Male,21,21,88,85,5,89,44,Fail
416,417,Male,17,30,75,52,3,60,52,Pass
417,418,Female,18,25,95,58,3,60,86,Pass
418,419,Female,17,32,99,57,10,44,85,Pass
419,420,Female,19,6,64,82,5,87,70,Pass
420,421,Female,17,5,83,55,10,59,94,Pass
421,422,Female,21,30,91,90,6,76,55,Pass
422,423,Female,22,33,93,88,8,42,89,Pass
423,424,Male,20,25,98,53,9,83,71,Pass
424,425,Female,17,15,89,62,4,72,61,Pass
425,426,Male,21,15,60,98,8,92,68,Pass
426,427,Male,21,39,52,51,3,48,61,Fail
427,428,Female,22,38,55,54,9,48,82,Fail
428,429,Male,19,28,58,93,1,43,42,Fail
429,430,Female,21,26,55,76,2,74,93,Fail
430,431,Male,21,9,58,81,10,56,49,Fail
431,432,Female,21,37,88,70,0,73,81,Pass
432,433,Male,21,24,80,57,5,63,60,Pass
433,434,Female,18,23,81,87,5,71,55,Pass
434,435,Female,18,39,90,57,0,40,51,Pass
435,436,Female,19,21,99,99,10,47,41,Fail
436,437,Female,17,38,61,52,2,84,80,Pass
437,438,Female,21,13,57,93,4,62,63,Fail
438,439,Male,22,30,57,52,2,86,74,Fail
439,440,Male,17,6,99,71,9,79,95,Pass
440,441,Male,22,13,77,55,2,51,69,Pass
441,442,Female,17,13,69,51,9,93,96,Pass
442,443,Male,19,21,96,72,2,51,69,Pass
443,444,Female,21,5,56,93,4,85,86,Fail
444,445,Female,21,29,60,51,4,86,74,Pass
445,446,Male,20,29,69,87,3,54,58,Pass
446,447,Male,22,39,65,66,0,80,89,Pass
447,448,Female,17,7,53,84,4,58,47,Fail
448,449,Male,17,34,55,83,9,65,65,Fail
449,450,Female,18,38,71,72,4,91,88,Pass
450,451,Female,20,16,75,79,3,68,79,Pass
451,452,Female,18,23,52,57,5,61,46,Fail
452,453,Female,18,21,90,71,9,79,69,Pass
453,454,Female,18,14,91,93,3,60,46,Fail
454,455,Male,22,16,63,85,6,90,42,Fail
455,456,Male,22,20,60,54,6,77,40,Fail
456,457,Female,19,28,67,62,1,59,75,Pass
457,458,Female,19,23,61,78,2,96,64,Pass
458,459,Male,18,12,72,80,0,68,76,Pass
459,460,Male,20,35,61,96,7,90,40,Fail
460,461,Female,17,25,62,65,8,43,54,Pass
461,462,Male,22,21,74,91,3,94,76,Pass
462,463,Female,20,27,94,79,5,46,52,Pass
463,464,Male,21,20,100,65,8,67,79,Pass
464,465,Female,22,10,68,61,5,67,47,Fail
465,466,Male,22,12,95,66,8,43,44,Fail
466,467,Female,19,29,85,65,3,61,99,Pass
467,468,Male,17,22,94,61,7,51,48,Fail
468,469,Male,17,29,57,57,8,84,40,Fail
469,470,Female,21,16,78,69,3,42,75,Pass
470,471,Male,21,19,81,52,4,61,74,Pass
471,472,Female,22,30,100,65,7,83,41,Fail
472,473,Male,18,30,93,79,9,41,79,Pass
473,474,Female,19,36,67,94,5,63,62,Pass
474,475,Male,19,14,55,72,6,73,48,Fail
475,476,Female,22,20,67,77,2,66,73,Pass
476,477,Male,20,11,68,89,6,94,85,Pass
477,478,Female,18,21,71,54,7,80,53,Pass
478,479,Male,22,27,86,69,9,40,43,Fail
479,480,Female,18,30,81,89,5,47,69,Pass
480,481,Female,18,25,90,93,9,62,70,Pass
481,482,Female,18,26,52,50,8,77,77,Fail
482,483,Male,22,11,77,79,5,45,50,Pass
483,484,Female,19,18,59,70,8,61,74,Fail
484,485,Male,19,19,100,69,3,64,47,Fail
485,486,Female,18,11,84,55,7,57,42,Fail
486,487,Male,20,13,78,71,10,56,53,Pass
487,488,Female,17,12,64,67,3,51,99,Pass
488,489,Male,22,27,82,57,1,45,52,Pass
489,490,Male,17,33,56,88,9,65,84,Fail
490,491,Female,20,22,61,81,10,66,71,Pass
491,492,Male,22,35,98,82,8,47,73,Pass
492,493,Male,18,34,79,65,4,58,84,Pass
493,494,Female,19,39,70,61,3,99,58,Pass
494,495,Male,17,22,80,87,1,81,98,Pass
495,496,Male,21,21,73,83,0,40,77,Pass
496,497,Male,21,18,69,63,10,96,55,Pass
497,498,Female,20,35,86,85,6,68,41,Fail
498,499,Male,18,28,53,82,5,84,79,Fail
499,500,Female,17,39,77,72,1,88,56,Pass