In [1]:
import pandas as pd

In [5]:
#reading the csv file
df_exams = pd.read_csv('student_performance.csv')
df_exams.head()

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result
0,1,Male,21,14,93,93,1,71,74,Pass
1,2,Female,21,21,94,69,1,95,79,Pass
2,3,Male,17,24,83,73,8,50,53,Pass
3,4,Male,19,28,52,99,4,59,74,Fail
4,5,Male,18,9,86,98,1,63,87,Pass

## 1 Selecting two or more Columns

In [9]:
# select 2 columns using [[]]
df_exams[['Gender', 'Age']]

     Gender  Age
0      Male   21
1    Female   21
2      Male   17
3      Male   19
4      Male   18
..      ...  ...
495    Male   21
496    Male   21
497  Female   20
498    Male   18
499  Female   17

[500 rows x 2 columns]

In [12]:
# check out the data type of the selection
type(df_exams[['Gender', 'Age']])
# [[]] represents dataframe while [] represents series(rows)

pandas.core.frame.DataFrame

In [18]:
# select two or more columns using [[]]
df_exams[['Attendance_Percentage',	'Assignments_Completed',	'Previous_Grade',	'Midterm_Score']]

,Attendance_Percentage,Assignments_Completed,Previous_Grade,Midterm_Score
0,93,1,93,71
1,94,1,69,95
2,83,8,73,50
3,52,4,99,59
4,86,1,98,63
...,...,...,...,...
495,73,0,83,40
496,69,10,63,96
497,86,6,85,68
498,53,5,82,84
499,77,1,72,88

In [19]:
# we can't use 2 or more columns using '.'