In [1]:
import pandas as pd
import numpy as np

In [4]:
# reading csv file
df_exams = pd.read_csv("student_performance.csv")
df_exams.head()

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result
0,1,Male,21,14,93,93,1,71,74,Pass
1,2,Female,21,21,94,69,1,95,79,Pass
2,3,Male,17,24,83,73,8,50,53,Pass
3,4,Male,19,28,52,99,4,59,74,Fail
4,5,Male,18,9,86,98,1,63,87,Pass

# 1 Math Operations

## 1.1 Operations in Columns

In [8]:
# select a column and calculate sum
df_exams['Midterm_Score'].sum().item()

34678

In [15]:
# calculate count, mean, std, max and min
print(df_exams['Midterm_Score'].mean())
print(df_exams['Midterm_Score'].count())
print(df_exams['Midterm_Score'].std())
print(df_exams['Midterm_Score'].max())
df_exams['Midterm_Score'].min()

69.356
500
17.420223660583964
99

40

In [17]:
# using .describe()
df_exams.describe()

,Student_ID,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.00000,500.000000,500.000000
mean,250.500000,19.462000,22.140000,75.146000,74.708000,4.84800,69.356000,70.310000
std,144.481833,1.715354,10.133201,14.435423,14.872967,3.04885,17.420224,17.167392
min,1.000000,17.000000,5.000000,50.000000,50.000000,0.00000,40.000000,40.000000
25%,125.750000,18.000000,13.000000,62.000000,61.750000,2.00000,55.000000,56.000000
50%,250.500000,20.000000,23.000000,76.000000,74.500000,5.00000,68.000000,72.000000
75%,375.250000,21.000000,30.000000,87.250000,88.000000,7.25000,85.000000,85.000000
max,500.000000,22.000000,39.000000,100.000000,99.000000,10.00000,99.000000,99.000000

## 1.2 Operations in Rows

In [20]:
# calculating the sum in a row
df_exams['Assignments_Completed'] +	df_exams['Midterm_Score'] +	df_exams['Final_Score']

0      146
1      175
2      111
3      137
4      151
      ...
495    117
496    161
497    115
498    168
499    145
Length: 500, dtype: int64

In [25]:
# calculating avg score and assigining it to a new column
df_exams["average"] = (df_exams['Assignments_Completed'] +	df_exams['Midterm_Score'] +	df_exams['Final_Score'])/3

In [26]:
# showing dataframe, .round(n) round-off upto n digits
df_exams.round(2)

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result,average
0,1,Male,21,14,93,93,1,71,74,Pass,48.67
1,2,Female,21,21,94,69,1,95,79,Pass,58.33
2,3,Male,17,24,83,73,8,50,53,Pass,37.00
3,4,Male,19,28,52,99,4,59,74,Fail,45.67
4,5,Male,18,9,86,98,1,63,87,Pass,50.33
...,...,...,...,...,...,...,...,...,...,...,...
495,496,Male,21,21,73,83,0,40,77,Pass,39.00
496,497,Male,21,18,69,63,10,96,55,Pass,53.67
497,498,Female,20,35,86,85,6,68,41,Fail,38.33
498,499,Male,18,28,53,82,5,84,79,Fail,56.00
499,500,Female,17,39,77,72,1,88,56,Pass,48.33

In [30]:
((df_exams['Midterm_Score']+df_exams['Final_Score'])/2).max()

98.5