In [17]:
import pandas as pd

In [18]:
# reading csv file
df_exams = pd.read_csv('student_performance.csv')
df_exams.head()

,Student_ID,Gender,Age,Study_Hours_per_Week,Attendance_Percentage,Previous_Grade,Assignments_Completed,Midterm_Score,Final_Score,Overall_Result,Parental_Level_of_Education
0,1,Male,21,14,93,93,1,71,74,Pass,Bachelor's Degree
1,2,Female,21,21,94,69,1,95,79,Pass,Bachelor's Degree
2,3,Male,17,24,83,73,8,50,53,Pass,PhD
3,4,Male,19,28,52,99,4,59,74,Fail,PhD
4,5,Male,18,9,86,98,1,63,87,Pass,Bachelor's Degree

# 1 Value Counts method

In [19]:
# counting gender elements

# len function
len(df_exams['Gender'])

# .count() method
df_exams['Gender'].count().item()

500

In [20]:
# counting elements by category
df_exams['Gender'].value_counts()

Gender
Female    256
Male      244
Name: count, dtype: int64

In [21]:
# return the relative frequency (divide all values by the sum of all values)
df_exams['Gender'].value_counts(normalize=True) #gives pecentage of each category

Gender
Female    0.512
Male      0.488
Name: proportion, dtype: float64

In [22]:
# counting "Parental_Level_of_Education" elements by category
df_exams['Parental_Level_of_Education'].value_counts()

Parental_Level_of_Education
PhD                  107
Associate Degree     104
High School          102
Bachelor's Degree     96
Master's Degree       91
Name: count, dtype: int64

In [23]:
# returns the the relative frequency and round to 2 decimal places
df_exams['Parental_Level_of_Education'].value_counts(normalize=True).round(2)

Parental_Level_of_Education
PhD                  0.21
Associate Degree     0.21
High School          0.20
Bachelor's Degree    0.19
Master's Degree      0.18
Name: proportion, dtype: float64