In [ ]:
import pandas as pd

In [ ]:
# read csv file
df = pd.read_csv('players_20.csv')
# set index
df.set_index('short_name', inplace = True)
# select columns
columns = ['long_name', 'age', 'dob', 'height_cm', 'weight_kg', 'nationality', 'club']

In [ ]:
# show df
df[columns]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

# 1.sample()

In [ ]:
# extract 10 random elements from the "nationality" column
df['nationality'].sample(10, random_state = 69) #random_state generates the same numbers everytime

short_name
Jordi Sánchez              Spain
A. Perez           United States
S. Al Faraj         Saudi Arabia
B. Jacobsen              Denmark
Riccieli                  Brazil
B. Bannan               Scotland
C. Peralta              Colombia
C. Baeza                   Chile
M. Dupé                   France
Edenildo Lagoas           Brazil
Name: nationality, dtype: object

In [ ]:
# extract a random 20% sample of the dataframe
df.sample(frac=0.2,random_state = 25)

,sofifa_id,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
short_name,,,,,,,,,,,,,,,,,,,,,
T. Durso,240955,https://sofifa.com/player/240955/tomas-durso/2...,Tomás Durso,20,1999-02-26,185,80,Argentina,Gimnasia y Esgrima La Plata,54,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Shim Dong Woon,207546,https://sofifa.com/player/207546/dong-woon-shi...,심원운 沈东云,29,1990-03-03,167,67,Korea Republic,Sangju Sangmu FC,70,...,58+2,55+2,55+2,55+2,58+2,57+2,50+2,50+2,50+2,57+2
K. Mouanga,247407,https://sofifa.com/player/247407/kevin-mouanga...,Kévin Mouanga,18,2000-07-24,191,80,France,Angers SCO,60,...,51+2,51+2,51+2,51+2,51+2,54+2,59+2,59+2,59+2,54+2
Pedro Pelágio,246866,https://sofifa.com/player/246866/pedro-henriqu...,Pedro Henrique Rocha Pelágio,19,2000-04-21,181,77,Portugal,Clube Sport Marítimo,66,...,61+2,60+2,60+2,60+2,61+2,58+2,55+2,55+2,55+2,58+2
D. Redan,246123,https://sofifa.com/player/246123/daishawn-reda...,Daishawn Redan,18,2001-02-02,177,68,Netherlands,Hertha BSC,61,...,41+2,37+2,37+2,37+2,41+2,39+2,35+2,35+2,35+2,39+2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
D. Benlamri,235499,https://sofifa.com/player/235499/djamel-eddine...,Djamel Eddine Benlamri,29,1989-12-25,185,83,Algeria,Al Shabab,74,...,63+2,67+2,67+2,67+2,63+2,65+2,72+2,72+2,72+2,65+2
O. Aina,224656,https://sofifa.com/player/224656/ola-aina/20/1...,Temitayo Olufisayo Olaoluwa Aina,22,1996-10-08,182,82,Nigeria,Torino,75,...,74+2,72+2,72+2,72+2,74+2,74+2,71+2,71+2,71+2,74+2
A. Manzur,242548,https://sofifa.com/player/242548/agustin-manzu...,Agustín Manzur,18,2000-09-29,169,65,Argentina,Godoy Cruz,57,...,54+2,56+2,56+2,56+2,54+2,54+2,55+2,55+2,55+2,54+2
L. Gibson,232648,https://sofifa.com/player/232648/liam-gibson/2...,Liam Gibson,22,1997-04-25,185,71,England,Grimsby Town,56,...,54+2,49+2,49+2,49+2,54+2,54+2,53+2,53+2,53+2,54+2
Bernard,205525,https://sofifa.com/player/205525/bernard-anici...,Bernard Anício Caldeira Duarte,26,1992-09-08,164,60,Brazil,Everton,80,...,62+2,56+2,56+2,56+2,62+2,58+2,45+2,45+2,45+2,58+2

In [ ]:
# upsample: increase the sampling rate -> frac>1 (Note : replace parameter has to be True for frac parameter > 1)
df.sample(frac=2, replace = True, random_state = 69)

,sofifa_id,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
short_name,,,,,,,,,,,,,,,,,,,,,
W. Saliba,243715,https://sofifa.com/player/243715/william-salib...,William Saliba,18,2001-03-24,192,85,France,AS Saint-Étienne,71,...,64+2,67+2,67+2,67+2,64+2,66+2,70+2,70+2,70+2,66+2
F. Ciampichetti,223665,https://sofifa.com/player/223665/flavio-ciampi...,Flavio Ciampichetti,31,1988-03-07,186,83,Argentina,KAS Eupen,66,...,43+2,43+2,43+2,43+2,43+2,42+2,47+2,47+2,47+2,42+2
E. Chilufya,242612,https://sofifa.com/player/242612/edward-chiluf...,Edward Chilufya,19,1999-09-17,171,68,Zambia,Djurgårdens IF,60,...,43+2,35+2,35+2,35+2,43+2,40+2,32+2,32+2,32+2,40+2
D. Haas,101488,https://sofifa.com/player/101488/daniel-haas/2...,Daniel Haas,35,1983-08-01,188,84,Germany,FC Erzgebirge Aue,64,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
L. Krajnc,205556,https://sofifa.com/player/205556/luka-krajnc/2...,Luka Krajnc,24,1994-09-19,187,86,Slovenia,Frosinone,71,...,64+2,65+2,65+2,65+2,64+2,65+2,69+2,69+2,69+2,65+2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Y. Maruyama,232848,https://sofifa.com/player/232848/yuichi-maruya...,丸山 祐市,30,1989-06-16,184,76,Japan,Nagoya Grampus,67,...,64+2,65+2,65+2,65+2,64+2,65+2,66+2,66+2,66+2,65+2
J. Peters,169158,https://sofifa.com/player/169158/jordens-peter...,Jordens Peters,32,1987-05-03,182,78,Netherlands,Willem II,68,...,61+2,66+2,66+2,66+2,61+2,62+2,67+2,67+2,67+2,62+2
L. Gabbichler,252266,https://sofifa.com/player/252266/lukas-gabbich...,Lukas Gabbichler,21,1998-05-12,186,75,Austria,TSV Hartberg,59,...,52+2,51+2,51+2,51+2,52+2,50+2,47+2,47+2,47+2,50+2
Lucas Leiva,176266,https://sofifa.com/player/176266/lucas-pezzini...,Lucas Pezzini Leiva,32,1987-01-09,179,78,Brazil,Lazio,84,...,77+3,81+3,81+3,81+3,77+3,77+3,79+3,79+3,79+3,77+3
C. Berra,156975,https://sofifa.com/player/156975/christophe-be...,Christophe Berra,34,1985-01-31,191,92,Scotland,Heart of Midlothian,71,...,54+2,61+2,61+2,61+2,54+2,57+2,70+2,70+2,70+2,57+2