In [4]:
import pandas as pd

In [5]:
# reading a csv file
df_laptops = pd.read_csv("laptop_price.csv")

In [6]:
df_laptops.head(3)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,MSI,Model_1,Ultrabook,14.8,2560x1600,AMD Ryzen 7 3.2GHz,32GB,256GB SSD,Nvidia RTX 3050,Windows 11,1.67,717.65
1,2,HP,Model_2,Notebook,16.8,2560x1600,Intel Core i5 2.3GHz,32GB,1TB SSD,Intel HD Graphics 620,No OS,2.45,1984.62
2,3,Asus,Model_3,Ultrabook,16.4,1920x1080,Intel Core i7 2.8GHz,16GB,1TB HDD,Intel HD Graphics 620,No OS,1.93,2096.84

# 1.Filter Dataframe based on one condition

In [8]:
# find which rows have "Apple" in the "Company" column
df_laptops['Company'] == 'Apple'

0      False
1      False
2      False
3      False
4      False
       ...
295    False
296    False
297     True
298    False
299    False
Name: Company, Length: 300, dtype: bool

In [9]:
# filter dataframe based on condition
df_laptops[df_laptops["Company"] == "Apple"]

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
18,19,Apple,Model_19,Business,15.4,1366x768,AMD Ryzen 7 3.2GHz,16GB,1TB SSD,Nvidia GTX 1650,macOS,1.94,734.62
20,21,Apple,Model_21,Ultrabook,14.2,1920x1080,AMD Ryzen 7 3.2GHz,16GB,256GB SSD,Intel Iris Plus Graphics 640,macOS,1.40,974.97
21,22,Apple,Model_22,Ultrabook,11.6,1920x1080,AMD Ryzen 5 2.1GHz,4GB,512GB SSD,Intel HD Graphics 620,Windows 11,1.46,690.81
32,33,Apple,Model_33,Ultrabook,16.0,2560x1600,Intel Core i7 2.8GHz,8GB,1TB SSD,Intel HD Graphics 6000,Windows 11,1.74,983.11
41,42,Apple,Model_42,Business,16.0,2256x1504,AMD Ryzen 5 2.1GHz,8GB,512GB SSD,Nvidia RTX 3050,Windows 10,1.43,1016.67
45,46,Apple,Model_46,Business,13.1,1920x1080,AMD Ryzen 5 2.1GHz,4GB,512GB SSD,Nvidia GTX 1650,Windows 11,2.41,2106.24
56,57,Apple,Model_57,Gaming,12.0,1920x1080,Intel Core i3 2.0GHz,4GB,256GB SSD,Nvidia RTX 3050,No OS,2.37,760.19
65,66,Apple,Model_66,Notebook,13.0,2256x1504,Intel Core i7 2.8GHz,16GB,256GB SSD,Intel HD Graphics 6000,Windows 11,1.52,1555.09
71,72,Apple,Model_72,Ultrabook,12.0,1440x900,Intel Core i3 2.0GHz,32GB,1TB SSD,Intel HD Graphics 620,Windows 11,1.19,1404.80
73,74,Apple,Model_74,Notebook,16.4,2560x1600,AMD Ryzen 5 2.1GHz,8GB,256GB SSD,Intel HD Graphics 6000,Windows 10,1.19,1348.41
95,96,Apple,Model_96,Ultrabook,16.5,1440x900,Intel Core i3 2.0GHz,32GB,128GB SSD,Intel Iris Plus Graphics 640,Windows 10,1.66,1158.81
97,98,Apple,Model_98,2 in 1 Convertible,14.4,1920x1080,Intel Core i3 2.0GHz,16GB,1TB SSD,Intel HD Graphics 620,No OS,1.53,568.26
100,101,Apple,Model_101,Gaming,15.9,1920x1080,AMD Ryzen 7 3.2GHz,8GB,1TB HDD,Nvidia GTX 1650,Windows 10,2.42,1540.22
101,102,Apple,Model_102,Gaming,11.8,2256x1504,AMD Ryzen 7 3.2GHz,8GB,512GB SSD,Intel HD Graphics 6000,Windows 11,2.28,667.43
102,103,Apple,Model_103,2 in 1 Convertible,13.8,1920x1080,AMD Ryzen 7 3.2GHz,4GB,256GB SSD,Intel HD Graphics 6000,Windows 10,1.46,1685.84
106,107,Apple,Model_107,2 in 1 Convertible,13.1,1920x1080,Intel Core i7 2.8GHz,4GB,1TB SSD,Intel HD Graphics 620,No OS,2.22,1813.12
115,116,Apple,Model_116,Gaming,16.4,1366x768,Intel Core i3 2.0GHz,32GB,128GB SSD,Intel HD Graphics 6000,No OS,1.74,1055.06
123,124,Apple,Model_124,Business,11.7,1440x900,Intel Core i3 2.0GHz,16GB,512GB SSD,Intel Iris Plus Graphics 640,macOS,2.06,1450.73
134,135,Apple,Model_135,Gaming,12.6,2560x1600,Intel Core i7 2.8GHz,4GB,128GB SSD,Intel HD Graphics 620,Windows 11,1.51,883.08
139,140,Apple,Model_140,Gaming,14.9,1366x768,Intel Core i5 2.3GHz,8GB,512GB SSD,Intel HD Graphics 620,No OS,1.60,593.35
150,151,Apple,Model_151,Ultrabook,14.6,1366x768,AMD Ryzen 5 2.1GHz,8GB,512GB SSD,Nvidia GTX 1650,Windows 11,2.44,1427.53
153,154,Apple,Model_154,Notebook,12.5,1920x1080,Intel Core i5 2.3GHz,4GB,256GB SSD,Intel HD Graphics 6000,macOS,1.14,944.91
155,156,Apple,Model_156,Gaming,12.3,1920x1080,AMD Ryzen 5 2.1GHz,32GB,1TB SSD,Intel HD Graphics 6000,No OS,1.15,1739.40
156,157,Apple,Model_157,Notebook,13.3,2256x1504,AMD Ryzen 5 2.1GHz,4GB,1TB HDD,Nvidia RTX 3050,No OS,2.22,496.24
178,179,Apple,Model_179,Notebook,13.4,1920x1080,Intel Core i3 2.0GHz,4GB,1TB SSD,Intel Iris Plus Graphics 640,Windows 11,1.88,2173.05
187,188,Apple,Model_188,Ultrabook,11.9,2256x1504,Intel Core i3 2.0GHz,8GB,1TB HDD,Nvidia RTX 3050,macOS,1.52,1137.65
188,189,Apple,Model_189,Notebook,12.9,2560x1600,AMD Ryzen 5 2.1GHz,32GB,512GB SSD,Intel Iris Plus Graphics 640,Windows 11,1.21,2118.41
190,191,Apple,Model_191,Ultrabook,12.5,1920x1080,AMD Ryzen 7 3.2GHz,4GB,1TB HDD,Nvidia GTX 1650,macOS,1.36,1968.65
193,194,Apple,Model_194,Notebook,12.1,1366x768,AMD Ryzen 5 2.1GHz,16GB,128GB SSD,Intel Iris Plus Graphics 640,Windows 10,1.35,625.08
208,209,Apple,Model_209,Notebook,14.9,2256x1504,Intel Core i7 2.8GHz,16GB,256GB SSD,Intel HD Graphics 6000,Windows 11,1.73,1289.23
216,217,Apple,Model_217,2 in 1 Convertible,12.8,2560x1600,Intel Core i5 2.3GHz,8GB,1TB HDD,Intel HD Graphics 620,No OS,1.81,679.28
229,230,Apple,Model_230,Gaming,12.1,1440x900,Intel Core i7 2.8GHz,16GB,1TB HDD,Nvidia RTX 3050,Windows 11,2.07,2469.35
233,234,Apple,Model_234,Business,17.1,1920x1080,AMD Ryzen 5 2.1GHz,4GB,1TB HDD,Nvidia RTX 3050,No OS,2.23,2268.34
237,238,Apple,Model_238,Gaming,14.7,2560x1600,AMD Ryzen 7 3.2GHz,16GB,1TB HDD,Intel HD Graphics 620,No OS,1.13,1048.83
238,239,Apple,Model_239,Business,12.8,1366x768,Intel Core i5 2.3GHz,8GB,1TB HDD,Intel HD Graphics 6000,macOS,2.26,1668.37
249,250,Apple,Model_250,Ultrabook,13.1,2560x1600,Intel Core i7 2.8GHz,4GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.58,2293.94
268,269,Apple,Model_269,2 in 1 Convertible,11.6,1920x1080,AMD Ryzen 5 2.1GHz,32GB,1TB SSD,Intel Iris Plus Graphics 640,No OS,2.23,656.62
275,276,Apple,Model_276,Gaming,14.2,2560x1600,AMD Ryzen 7 3.2GHz,8GB,1TB SSD,Intel HD Graphics 620,No OS,1.89,1218.94
278,279,Apple,Model_279,Notebook,17.3,1440x900,Intel Core i7 2.8GHz,4GB,512GB SSD,Intel HD Graphics 6000,No OS,2.04,556.88
279,280,Apple,Model_280,Business,12.0,2560x1600,AMD Ryzen 5 2.1GHz,8GB,512GB SSD,Intel HD Graphics 620,No OS,1.73,1672.60
283,284,Apple,Model_284,2 in 1 Convertible,16.5,2560x1600,AMD Ryzen 5 2.1GHz,4GB,512GB SSD,Nvidia GTX 1650,Windows 10,2.43,1999.38
293,294,Apple,Model_294,Business,12.9,1920x1080,Intel Core i3 2.0GHz,32GB,1TB HDD,Intel Iris Plus Graphics 640,macOS,2.16,2373.98
297,298,Apple,Model_298,Business,12.4,2256x1504,AMD Ryzen 7 3.2GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.26,2056.10

In [10]:
# verify which companiea are in the "Company" with value counts
df_laptops[df_laptops["Company"] == "Apple"].value_counts("Company")

Company
Apple    43
Name: count, dtype: int64

## 1.1 Exercise 1

In [12]:
# find which rows don't have "HP" in the "Company" column
df_laptops["Company"] != "HP"

0       True
1      False
2       True
3      False
4       True
       ...
295     True
296     True
297     True
298     True
299     True
Name: Company, Length: 300, dtype: bool

In [16]:
# filter dataframe based on condition
df_laptops[df_laptops["Company"] != "HP"].value_counts("Company")

Company
Apple        43
Microsoft    43
MSI          33
Acer         33
Samsung      31
Asus         31
Dell         29
Lenovo       25
Name: count, dtype: int64

## 1.2 Exercise 2

In [17]:
# find laptop with price over 2000 euros
df_laptops[df_laptops["Price_euros"] > 2000]

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
2,3,Asus,Model_3,Ultrabook,16.4,1920x1080,Intel Core i7 2.8GHz,16GB,1TB HDD,Intel HD Graphics 620,No OS,1.93,2096.84
7,8,Lenovo,Model_8,Notebook,11.7,1366x768,Intel Core i3 2.0GHz,8GB,256GB SSD,Intel Iris Plus Graphics 640,macOS,1.71,2479.82
9,10,HP,Model_10,2 in 1 Convertible,15.3,2256x1504,Intel Core i5 2.3GHz,8GB,512GB SSD,Intel Iris Plus Graphics 640,No OS,1.85,2132.89
14,15,Asus,Model_15,Gaming,14.6,1366x768,Intel Core i5 2.3GHz,32GB,1TB SSD,Intel HD Graphics 6000,macOS,2.17,2190.41
24,25,Lenovo,Model_25,Notebook,13.0,2256x1504,Intel Core i7 2.8GHz,16GB,1TB SSD,Nvidia RTX 3050,No OS,1.42,2250.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...
287,288,Asus,Model_288,Ultrabook,13.2,1920x1080,Intel Core i7 2.8GHz,32GB,256GB SSD,Intel Iris Plus Graphics 640,No OS,2.50,2035.50
290,291,HP,Model_291,Ultrabook,16.1,2256x1504,AMD Ryzen 7 3.2GHz,16GB,1TB SSD,Nvidia GTX 1650,Windows 11,1.71,2170.11
293,294,Apple,Model_294,Business,12.9,1920x1080,Intel Core i3 2.0GHz,32GB,1TB HDD,Intel Iris Plus Graphics 640,macOS,2.16,2373.98
294,295,Microsoft,Model_295,Notebook,12.9,1920x1080,AMD Ryzen 7 3.2GHz,16GB,1TB HDD,Intel Iris Plus Graphics 640,macOS,1.99,2302.95
297,298,Apple,Model_298,Business,12.4,2256x1504,AMD Ryzen 7 3.2GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.26,2056.10