In [1]:
import pandas as pd
import numpy as np

In [3]:
# reading a csv file
df_laptops = pd.read_csv('laptop_price.csv')

In [4]:
# show dataframe
df_laptops.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,MSI,Model_1,Ultrabook,14.8,2560x1600,AMD Ryzen 7 3.2GHz,32GB,256GB SSD,Nvidia RTX 3050,Windows 11,1.67,717.65
1,2,HP,Model_2,Notebook,16.8,2560x1600,Intel Core i5 2.3GHz,32GB,1TB SSD,Intel HD Graphics 620,No OS,2.45,1984.62
2,3,Asus,Model_3,Ultrabook,16.4,1920x1080,Intel Core i7 2.8GHz,16GB,1TB HDD,Intel HD Graphics 620,No OS,1.93,2096.84
3,4,HP,Model_4,2 in 1 Convertible,16.5,2256x1504,AMD Ryzen 5 2.1GHz,16GB,128GB SSD,Intel HD Graphics 6000,macOS,1.53,1353.78
4,5,Samsung,Model_5,Gaming,15.5,2560x1600,Intel Core i7 2.8GHz,32GB,1TB SSD,Intel Iris Plus Graphics 640,Windows 10,2.10,1990.95

# 1.isin() : Single Filtering
# is in method

In [5]:
# select Apple or HP laptops
df_laptops['Company'].isin(['Apple', 'HP'])

0      False
1       True
2      False
3       True
4      False
       ...
295    False
296    False
297     True
298    False
299    False
Name: Company, Length: 300, dtype: bool

In [7]:
 # filter dataframes and use value_counts
df_laptops[df_laptops['Company'].isin(['Apple', 'HP'])].value_counts('Company')

Company
Apple    43
HP       32
Name: count, dtype: int64

# 2.isin(): Multiple Filtering

In [10]:
# find notebooks or ultrabooks from Apple or HP laptops
f1 = df_laptops['TypeName'].isin(['Notebook','Ultrabook'])
f2 = df_laptops['Company'].isin(['Apple', 'HP'])

In [13]:
#filter dataframe
df_laptops[f1 & f2]

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
1,2,HP,Model_2,Notebook,16.8,2560x1600,Intel Core i5 2.3GHz,32GB,1TB SSD,Intel HD Graphics 620,No OS,2.45,1984.62
11,12,HP,Model_12,Notebook,14.5,2256x1504,AMD Ryzen 5 2.1GHz,4GB,512GB SSD,Nvidia RTX 3050,Windows 10,2.13,1255.71
20,21,Apple,Model_21,Ultrabook,14.2,1920x1080,AMD Ryzen 7 3.2GHz,16GB,256GB SSD,Intel Iris Plus Graphics 640,macOS,1.40,974.97
21,22,Apple,Model_22,Ultrabook,11.6,1920x1080,AMD Ryzen 5 2.1GHz,4GB,512GB SSD,Intel HD Graphics 620,Windows 11,1.46,690.81
25,26,HP,Model_26,Notebook,14.5,1920x1080,AMD Ryzen 5 2.1GHz,8GB,256GB SSD,Intel HD Graphics 6000,macOS,2.22,1933.06
32,33,Apple,Model_33,Ultrabook,16.0,2560x1600,Intel Core i7 2.8GHz,8GB,1TB SSD,Intel HD Graphics 6000,Windows 11,1.74,983.11
43,44,HP,Model_44,Notebook,14.5,2256x1504,Intel Core i7 2.8GHz,16GB,1TB SSD,Nvidia RTX 3050,Windows 11,1.66,2362.16
59,60,HP,Model_60,Ultrabook,17.0,1920x1080,Intel Core i5 2.3GHz,4GB,1TB HDD,Nvidia GTX 1650,No OS,2.25,1620.73
64,65,HP,Model_65,Ultrabook,16.6,1440x900,AMD Ryzen 7 3.2GHz,4GB,256GB SSD,Intel Iris Plus Graphics 640,Windows 10,2.36,1792.72
65,66,Apple,Model_66,Notebook,13.0,2256x1504,Intel Core i7 2.8GHz,16GB,256GB SSD,Intel HD Graphics 6000,Windows 11,1.52,1555.09
69,70,HP,Model_70,Ultrabook,12.8,2256x1504,Intel Core i7 2.8GHz,4GB,1TB HDD,Intel Iris Plus Graphics 640,Windows 11,2.15,476.56
71,72,Apple,Model_72,Ultrabook,12.0,1440x900,Intel Core i3 2.0GHz,32GB,1TB SSD,Intel HD Graphics 620,Windows 11,1.19,1404.80
73,74,Apple,Model_74,Notebook,16.4,2560x1600,AMD Ryzen 5 2.1GHz,8GB,256GB SSD,Intel HD Graphics 6000,Windows 10,1.19,1348.41
81,82,HP,Model_82,Ultrabook,16.7,2256x1504,Intel Core i3 2.0GHz,16GB,1TB SSD,Nvidia RTX 3050,Windows 11,1.98,1905.34
95,96,Apple,Model_96,Ultrabook,16.5,1440x900,Intel Core i3 2.0GHz,32GB,128GB SSD,Intel Iris Plus Graphics 640,Windows 10,1.66,1158.81
121,122,HP,Model_122,Ultrabook,15.4,1920x1080,Intel Core i3 2.0GHz,4GB,512GB SSD,Intel Iris Plus Graphics 640,Windows 10,1.54,1134.34
127,128,HP,Model_128,Notebook,16.4,1366x768,Intel Core i7 2.8GHz,8GB,1TB HDD,Nvidia RTX 3050,macOS,2.01,470.05
150,151,Apple,Model_151,Ultrabook,14.6,1366x768,AMD Ryzen 5 2.1GHz,8GB,512GB SSD,Nvidia GTX 1650,Windows 11,2.44,1427.53
152,153,HP,Model_153,Ultrabook,16.8,1440x900,Intel Core i3 2.0GHz,8GB,256GB SSD,Intel Iris Plus Graphics 640,macOS,2.10,1926.74
153,154,Apple,Model_154,Notebook,12.5,1920x1080,Intel Core i5 2.3GHz,4GB,256GB SSD,Intel HD Graphics 6000,macOS,1.14,944.91
156,157,Apple,Model_157,Notebook,13.3,2256x1504,AMD Ryzen 5 2.1GHz,4GB,1TB HDD,Nvidia RTX 3050,No OS,2.22,496.24
171,172,HP,Model_172,Ultrabook,12.2,2256x1504,Intel Core i5 2.3GHz,4GB,1TB SSD,Nvidia RTX 3050,Windows 11,2.36,2429.21
178,179,Apple,Model_179,Notebook,13.4,1920x1080,Intel Core i3 2.0GHz,4GB,1TB SSD,Intel Iris Plus Graphics 640,Windows 11,1.88,2173.05
187,188,Apple,Model_188,Ultrabook,11.9,2256x1504,Intel Core i3 2.0GHz,8GB,1TB HDD,Nvidia RTX 3050,macOS,1.52,1137.65
188,189,Apple,Model_189,Notebook,12.9,2560x1600,AMD Ryzen 5 2.1GHz,32GB,512GB SSD,Intel Iris Plus Graphics 640,Windows 11,1.21,2118.41
190,191,Apple,Model_191,Ultrabook,12.5,1920x1080,AMD Ryzen 7 3.2GHz,4GB,1TB HDD,Nvidia GTX 1650,macOS,1.36,1968.65
193,194,Apple,Model_194,Notebook,12.1,1366x768,AMD Ryzen 5 2.1GHz,16GB,128GB SSD,Intel Iris Plus Graphics 640,Windows 10,1.35,625.08
208,209,Apple,Model_209,Notebook,14.9,2256x1504,Intel Core i7 2.8GHz,16GB,256GB SSD,Intel HD Graphics 6000,Windows 11,1.73,1289.23
249,250,Apple,Model_250,Ultrabook,13.1,2560x1600,Intel Core i7 2.8GHz,4GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.58,2293.94
262,263,HP,Model_263,Ultrabook,14.6,1920x1080,Intel Core i5 2.3GHz,32GB,1TB HDD,Intel Iris Plus Graphics 640,Windows 10,1.76,1585.65
265,266,HP,Model_266,Ultrabook,13.3,1920x1080,Intel Core i7 2.8GHz,8GB,128GB SSD,Nvidia GTX 1650,Windows 10,2.36,2368.78
278,279,Apple,Model_279,Notebook,17.3,1440x900,Intel Core i7 2.8GHz,4GB,512GB SSD,Intel HD Graphics 6000,No OS,2.04,556.88
284,285,HP,Model_285,Notebook,15.8,1440x900,AMD Ryzen 7 3.2GHz,8GB,1TB SSD,Intel HD Graphics 6000,macOS,2.32,1729.04
290,291,HP,Model_291,Ultrabook,16.1,2256x1504,AMD Ryzen 7 3.2GHz,16GB,1TB SSD,Nvidia GTX 1650,Windows 11,1.71,2170.11

In [14]:
# count
df_laptops[f1 & f2].value_counts('Company')

Company
Apple    18
HP       16
Name: count, dtype: int64