In [89]:
import pandas as pd

In [90]:
df_movies = pd.read_csv('IMDb movies.csv', engine='python', on_bad_lines = 'skip')
df_ratings = pd.read_csv('IMDb ratings.csv')

In [91]:
df_movies = df_movies[['imdb_title_id', 'title', 'year','genre', 'country']]
df_ratings = df_ratings[['imdb_title_id', 'total_votes', 'mean_vote']]

# 1 concat()

## 1.1 Concatenate Vertically

In [92]:
df1 = pd.DataFrame({
    'id' : ['A', 'B', 'C', 'D'],
    'age' : [30, 23, 32, 22]
})

df2 = pd.DataFrame({
    'id' : ['E', 'F', 'G', 'H'],
    'age' : [40, 21, 19, 24]
})

In [93]:
pd.concat([df1, df2], axis = 0, ignore_index = True)

  id  age
0  A   30
1  B   23
2  C   32
3  D   22
4  E   40
5  F   21
6  G   19
7  H   24

### 1.1.1 exercise

In [94]:
# exctract a 50% sample of the original dataframe (df_movies)
df_sample = df_movies.sample(frac = 0.5)

In [95]:
# shape of dataframes that we'll concatenate
print(df_movies.shape)
df_sample.shape

(85855, 5)

(42928, 5)

In [96]:
# concatenate df_movies and df_sample (vertically along the rows)
df_concat_vertically = pd.concat([df_movies, df_sample], axis = 0)

In [97]:
# shape
df_concat_vertically.shape

(128783, 5)

## 1.2 Concatenate Horizontally

In [98]:
df1 = pd.DataFrame({
    'id' : ['A', 'B', 'C', 'D'],
    'age' : [30, 23, 25, 22]
})

df2 = pd.DataFrame({
    'job' : ['Doctor', 'Statistician', 'Accountant', 'Developer'],
})

In [99]:
pd.concat([df1, df2], axis = 1)

  id  age           job
0  A   30        Doctor
1  B   23  Statistician
2  C   25    Accountant
3  D   22     Developer

### 1.2.1 exercise

In [100]:
# shape of dataframes that we'll concatenate
print(df_movies.shape)
df_ratings.shape

(85855, 5)

(85855, 3)

In [101]:
df_movies.set_index('imdb_title_id', inplace = True)
df_ratings.set_index('imdb_title_id', inplace = True)

In [102]:
# concatenate df_movies and df_ratings on 'imdb_title_id' (horizontally)

df_concat_horizontally = pd.concat([df_movies, df_ratings], axis = 1)
df_concat_horizontally

,title,year,genre,country,total_votes,mean_vote
imdb_title_id,,,,,,
tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...
tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

In [104]:
# shape
df_concat_horizontally.shape

(85855, 6)